export const PRODUCTS_ALL = 'PRODUCTS_ALL';
export const PRODUCTS_PRODUCT = 'PRODUCTS_PRODUCT';
export const PRODUCTS_STORE = 'PRODUCTS_STORE';
export const PRODUCTS_UPDATE = 'PRODUCTS_UPDATE';
export const PRODUCTS_DESTROY = 'PRODUCTS_DESTROY';
export const PRODUCTS_SEARCH = 'PRODUCTS_SEARCH';
